// lib/brands.ts

export const WATCH_BRANDS: string[] = [
  "Akin", "Akrivia", "Alexander Shorokhoff", "Alpina", "Angelus", "Anordain", 
  "Antoine Preziuso", "Armin Strom", "Arnold & Son", "ArtyA", "Askania", 
  "Audemars Piguet", "Autodromo", "Ball Watch Company", "Baltic Watches", 
  "Bamford Watch Department", "Bell & Ross", "Benrus", "Bermont", "Berneron", 
  "Biolley", "Blancpain", "Blaken", "Bravur", "Breguet", "Breitling", "Bremont", 
  "Bulgari", "Bulova", "Bvlgari", "Ciga Design", "Carl F. Bucherer", "Cartier", 
  "Casio", "Cedric Johner", "Certina", "Chanel", "Chopard", "Christopher Ward", 
  "Chronoswiss", "Citizen", "Claude Meylan", "Clemence Watches", "Constantin Chaykin", 
  "Corum", "Czapek & Cie", "Daniel Roth", "Dan Henry", "David Candaux", 
  "De Bethune", "DeLaneau", "DeWitt", "Direnzo", "Doxa", "Dufour", "Dufrane", 
  "Ebel", "Eberhard & Co.", "Edox", "Edward Hornby", "Epos", "Eterna", 
  "Excelsior Park", "F.P. Journe", "Farer", "Fears", "Ferdinand Berthoud", 
  "Formex", "Fortis", "Furlan Marri", "Gallet", "Garrick", "George Daniels", 
  "Girard-Perregaux", "Glycine", "Gorilla Watches", "Greubel Forsey", "G-Shock", 
  "Gucci", "H. Moser & Cie.", "Haldimann", "Hamilton", "Hanhart", "Harry Winston", 
  "Hautlence", "Heuer", "Hublot", "HYT", "IWC Schaffhausen", "Ikepod", "Incipio", 
  "Invicta", "Itay Noy", "Jaeger-LeCoultre", "Jaquet Droz", "Jean Richard", 
  "Jean-Claude Biver", "Jean Rousseau", "Julien Coudray", "Junghans", 
  "Kari Voutilainen", "Karsten Frässdorf", "Krayon", "Kudoke", "Kurono Tokyo", 
  "Laco", "Lang & Heyne", "Laurent Ferrier", "Le Regulator", "Linde Werdelin", 
  "Lip", "Longines", "Lorier", "Louis Erard", "Louis Moinet", "Louis Vuitton", 
  "Lucian Piccard", "Ludovic Ballouard", "M.A.D.Edition", "Marathon", "Marnaut", 
  "Massena LAB", "Maurice de Mauriac", "Maurice Lacroix", "MB&F", "Meistersinger", 
  "Merkur", "Microma", "Mido", "Ming", "Minase", "Moonswatch", "Montblanc", 
  "Moritz Grossmann", "Nezumi", "Nivada Grenchen", "Norqain", "Ochs und Junior", 
  "Ollech & Wajs", "Omega", "Oris", "Panerai", "Parmigiani Fleurier", 
  "Patek Philippe", "Pequignet", "Perrelet", "Petermann Bedat", "Piaget", 
  "Pierre DeRoche", "Porsche Design", "ProTek", "Pulsar", "Q Timex", "Rado", 
  "Raidillon", "Raketa", "Raymond Weil", "Resence", "Ressence", "Rexhep Rexhepi", 
  "Richard Mille", "Roger Dubuis", "Roger W. Smith", "Rolex", "Romain Gauthier", 
  "Romain Jerome", "RUF", "Sandoz", "Sarpaneva", "Sartory Billard", 
  "Schaumburg Watch", "Schofield", "Schwarz Etienne", "Sea-Gull", "Seiko", 
  "Serica", "Sherpa Watches", "Shinola", "Sinn", "Singer Reimagined", "Smiths", 
  "Solios", "Speake-Marin", "Squale", "Studio Underd0g", "Stowa", "Suunto", 
  "Swarovski", "Swatch", "TAG Heuer", "Takashi", "Tudor", "Tissot", "Traska", 
  "Twelve", "TW Steel", "U-Boat", "Ulysse Nardin", "Unimatic", "Universal Geneve", 
  "Urwerk", "Vacheron Constantin", "Van Cleef & Arpels", "Vanguard", 
  "Vianney Halter", "Victorinox", "Vortic", "Voutilainen", "Waltham", 
  "Weiss Watch Company", "Welsbro", "Wempe", "William Wood", "Wittnauer", 
  "Wyler Vetta", "Xicorr", "Yema", "Zannetti", "Zelos Watches", "Zenith", "Zodiac",
  
  // Collaborative & Special Designations
  "Louis Erard x Alain Silberstein",
  "Louis Erard x seconde/seconde",
  "Louis Erard x Konstantin Chaykin",
  "Louis Erard x Massena LAB",
  "MB&F x H. Moser",
  "MB&F x L'Epée",
  "Omega x Swatch (MoonSwatch)",
  "Blancpain x Swatch",
  "TAG Heuer x Porsche",
  "Tudor x Marine Nationale"
];