// lib/brands.ts

export const WATCH_BRANDS: string[] = [
  "Akin", "Akrivia", "Alexander Shorokhoff", "Alpina", "Angelus", "Anordain", 
  "Antoine Martin", "Antoine Preziuso", "Armin Strom", "Arnold & Son", "ArtyA", "Askania", 
  "Audemars Piguet", "Autodromo", "Ball Watch Company", "Baltic Watches", 
  "Bamford Watch Department", "Bell & Ross", "Benrus", "Bermont", "Berneron", 
  "Biolley", "Blancpain", "Blaken", "Bovet", "Bravur", "Breguet", "Breitling", "Bremont", 
  "Bulgari", "Bulova", "Bvlgari", "Ciga Design", "Carl F. Bucherer", "Cartier", 
  "Casio", "Cedric Johner", "Certina", "Chanel", "Chopard", "Christopher Ward", 
  "Chronoswiss", "Citizen", "Claude Meylan", "Clemence Watches", "Constantin Chaykin", 
  "Corum", "Credor", "Czapek & Cie", "Daniel Roth", "Dan Henry", "David Candaux", 
  "De Bethune", "DeLaneau", "DeWitt", "Direnzo", "Doxa", "Dubey & Schaldenbrand", "Dufour", 
  "Dufrane", "Ebel", "Eberhard & Co.", "Edox", "Edward Hornby", "Enicar", "Epos", "Elka Watch Co.", "Eterna", 
  "Excelsior Park", "F.P. Journe", "Farer", "Favre-Leuba", "Fears", "Ferdinand Berthoud", 
  "Formex", "Fortis", "Franck Muller", "Frédérique Constant", "Furlan Marri", "Gallet", "Garrick", 
  "George Daniels", "Gerald Genta", "Girard-Perregaux", "Glashütte Original", "Glycine", 
  "Gorilla Watches", "Grand Seiko", "Greubel Forsey", "G-Shock", 
  "Gucci", "H. Moser & Cie.", "Haldimann", "Halios", "Hamilton", "Hanhart", "Harry Winston", 
  "Hautlence", "Heuer", "Hublot", "HYT", "IWC Schaffhausen", "Ikepod", "Incipio", 
  "Invicta", "Itay Noy", "Jaeger-LeCoultre", "Jaquet Droz", "Jean Richard", 
  "Jean-Claude Biver", "Jean Rousseau", "Julien Coudray", "Junghans", "Kallinich Claeys", 
  "Kari Voutilainen", "Karsten Frässdorf", "Krayon", "Kudoke", "Kurono Tokyo", 
  "Laco", "Lang & Heyne", "Laurent Ferrier", "Leinfelder", "Le Regulator", "Linde Werdelin", 
  "Lip", "Longines", "Lorier", "Louis Erard", "Louis Moinet", "Louis Vuitton", 
  "Lucian Piccard", "Ludovic Ballouard", "M.A.D.Edition", "Magrette", "Marathon", "Marc Newson", 
  "Marco Lang", "Marnaut", "Martin Braun", "Massena LAB", "Maurice de Mauriac", "Maurice Lacroix", "MB&F", 
  "Meistersinger", "Merkur", "Microma", "Mido", "Milus", "Ming", "Minase", "Moonswatch", "Montblanc", 
  "Moritz Grossmann", "Muhle", "NBY", "Nezumi", "Nienaber", "Nivada Grenchen", "Nomos Glashütte", 
  "Norqain", "Ochs und Junior", "Ollech & Wajs", "Omega", "Ondrej Berkus", "Oris", "Panerai", "Parmigiani Fleurier", 
  "Patek Philippe", "Patria Watch Co.", "Paul Picot", "Pegasus Watches", "Pequignet", "Perrelet", 
  "Petermann Bedat", "Peter Speake",  "Piaget", "Pierre DeRoche", "Poljot", "Porsche Design", "ProTek", "Pulsar", 
  "Q Timex", "Rado", "Raidillon", "Raketa", "Raymond Weil", "Resence", "Ressence", "Rexhep Rexhepi", 
  "Richard Mille", "Roger Dubuis", "Roger W. Smith", "Rolex", "Romain Gauthier", 
  "Romain Jerome", "RUF", "Sandoz", "Sarpaneva", "Sartory Billard", 
  "Schaumburg Watch", "Schofield", "Schwarz Etienne", "Sea-Gull", "Seiko", 
  "Serica", "Sherpa Watches", "Shinola", "Sinn", "Singer Reimagined", "Smiths", 
  "Solios", "Speake-Marin", "Squale", "Struthers Watchmakers", "Studio Underd0g", "Stowa", "S.U.F Helsinki", 
  "Sufian", "Sully", "Suunto", "Swarovski", "Swatch", "Sylvain Pinaud", "TAG Heuer", "Takashi", "Tan Zehua", 
  "Thomas Prescher", "Tissot", "Traska", "Tudor", "Tutima Glashütte", "Twelve", "TW Steel", "U-Boat", "Ulysse Nardin", 
  "Unimatic", "Universal Geneve", "Urwerk", "Vacheron Constantin", "Valerii Danevych", 
  "Van Cleef & Arpels", "Vanguard", "Vianney Halter", "Victorinox", "Vicent Calabrese", "Vortic", 
  "Voutilainen", "Vulcain", "Waltham", "Weiss Watch Company", "Welsbro", "Wempe", "William Wood", 
  "Wittnauer", "Wyler Vetta", "Xhevdet Rexhepi", "Xicorr", "Yema", "Yonger & Bresson", "Zannetti", "Zeitwinkel", 
  "Zelos Watches", "Zenith", "Zim", "Zodiac",
  
  // Collaborative & Special Designations
  "Louis Erard x Alain Silberstein",
  "Louis Erard x seconde/seconde",
  "Louis Erard x Konstantin Chaykin",
  "Louis Erard x Massena LAB",
  "MB&F x H. Moser",
  "MB&F x L'Epée",
  "Omega x Swatch (MoonSwatch)",
  "Blancpain x Swatch",
  "TAG Heuer x Porsche",
  "Tudor x Marine Nationale"
];