/* Vault Specification Upgrade — closed v3.2 contract tests.
   Run: node scripts/vault-upgrade-contract.test.mjs */
import assert from "node:assert/strict";
import {
  encode,
  fixtureJson,
  fixtureBytes,
  loadEngine,
} from "./vault-upgrade-fixtures/engine-helper.mjs";

const { engine } = await loadEngine();
let pass = 0;
const ok = (name, condition) => {
  assert.ok(condition, name);
  pass++;
};

const analyze = (filename, value) =>
  engine.analyzeSource({ filename, bytes: encode(value) });
const base = () => fixtureJson("current-v3.2.json");

// Exact valid v3.2 file — success no-op, nothing invented, nothing changed.
{
  const r = await engine.analyzeSource({
    filename: "current-v3.2.json",
    bytes: fixtureBytes("current-v3.2.json"),
  });
  ok("valid v3.2 → CURRENT_SPEC_NO_CHANGE", r.status === "CURRENT_SPEC_NO_CHANGE");
  ok("valid v3.2 → zero issues", r.issues.length === 0);
  ok("valid v3.2 → zero ledger rows", r.ledger.length === 0);
  ok("valid v3.2 → no candidate generated by default", r.candidate === null);
  ok(
    "detection is CURRENT_CONTRACT / STRUCTURALLY_UNIQUE",
    r.detection.sourceContract === "CURRENT_CONTRACT" &&
      r.detection.certaintyClass === "STRUCTURALLY_UNIQUE"
  );
}

// Missing required factual field → RESEARCH_REQUIRED with the exact path.
{
  const doc = base();
  delete doc.description;
  const r = await analyze("missing-description.json", doc);
  ok("missing description → RESEARCH_REQUIRED", r.status === "RESEARCH_REQUIRED");
  ok(
    "missing description path reported",
    r.issues.some(
      (i) => i.path === "/description" && i.code === "MISSING_REQUIRED_FACT"
    )
  );
  ok("missing fact never yields a candidate", r.candidate === null);
}

// Unsupported field at every hierarchy level → BLOCKED, values preserved.
{
  const r = await engine.analyzeSource({
    filename: "unsupported-fields.json",
    bytes: fixtureBytes("unsupported-fields.json"),
  });
  ok("unsupported fields → BLOCKED", r.status === "BLOCKED");
  const paths = r.issues
    .filter((i) => i.code === "UNSUPPORTED_SCHEMA_FIELD")
    .map((i) => i.path);
  ok("brand-level unknown field reported", paths.includes("/founded_year"));
  ok(
    "collection-level unknown field reported",
    paths.includes("/Collections/0/marketing_tagline")
  );
  ok(
    "family-level unknown field reported",
    paths.includes("/Collections/0/Families/0/price_band")
  );
  ok(
    "variant-level unknown field reported",
    paths.includes("/Collections/0/Families/0/Variants/0/rarity_score")
  );
  ok(
    "reference-level unknown field reported",
    paths.includes(
      "/Collections/0/Families/0/Variants/0/references/0/market_value"
    )
  );
  const founded = r.issues.find((i) => i.path === "/founded_year");
  ok("unknown field value preserved exactly", founded.value === 1994);
  ok("blocked file has no candidate", r.candidate === null);
}

// Invalid field type → DECISION_REQUIRED.
{
  const doc = base();
  doc.search_aliases = "not-an-array";
  const r = await analyze("bad-type.json", doc);
  ok("invalid type → DECISION_REQUIRED", r.status === "DECISION_REQUIRED");
  ok(
    "type violation reported at exact path",
    r.issues.some(
      (i) =>
        i.path === "/search_aliases" && i.code === "VALUE_DECISION_REQUIRED"
    )
  );
}

// revival_type present when not revived → conflict, never silently fixed.
{
  const doc = base();
  doc.revival_type = "original"; // revival_status is "active" in the fixture
  const r = await analyze("type-without-revived.json", doc);
  ok(
    "revival_type on active brand → DECISION_REQUIRED",
    r.status === "DECISION_REQUIRED"
  );
  ok(
    "conditional violation reported",
    r.issues.some(
      (i) =>
        i.path === "/revival_type" && i.code === "CONDITIONAL_VIOLATION"
    )
  );
}

// Revived without revival_type → the HOW is a missing fact.
{
  const doc = base();
  doc.revival_status = "revived";
  const r = await analyze("revived-without-type.json", doc);
  ok(
    "revived without revival_type → RESEARCH_REQUIRED",
    r.status === "RESEARCH_REQUIRED"
  );
  ok(
    "revival_type reported as missing fact with permitted values",
    r.issues.some(
      (i) =>
        i.path === "/revival_type" &&
        i.code === "MISSING_REQUIRED_FACT" &&
        i.allowedValues?.join(",") === "original,acquired"
    )
  );
}

// Contradictory historical_continuity → decision, both directions.
{
  const doc = base();
  doc.historical_continuity = "revived"; // revival_status stays "active"
  const r = await analyze("contradictory-continuity.json", doc);
  ok(
    "continuity revived vs status active → DECISION_REQUIRED",
    r.status === "DECISION_REQUIRED"
  );
  const doc2 = base();
  doc2.revival_status = "discontinued";
  doc2.historical_continuity = "interrupted";
  const r2 = await analyze("interrupted-discontinued.json", doc2);
  ok(
    "continuity interrupted vs status discontinued → DECISION_REQUIRED",
    r2.status === "DECISION_REQUIRED"
  );
}

// Enum violation carries the permitted vocabulary.
{
  const doc = base();
  doc.cluster = "Space Watches";
  const r = await analyze("bad-cluster.json", doc);
  ok("unknown cluster → DECISION_REQUIRED", r.status === "DECISION_REQUIRED");
  const issue = r.issues.find((i) => i.path === "/cluster");
  ok(
    "cluster issue lists permitted values",
    issue?.allowedValues?.includes("Heritage Swiss")
  );
  ok("cluster issue preserves exact value", issue?.value === "Space Watches");
}

console.log(`vault-upgrade-contract: ${pass} assertions PASS`);
